### ISSUE TITLE
method get_title_reviews() returns only the first 10 reviews of a movie

### ISSUE THREAD

**Issue by adalex2001** [richardasaurus/imdb-pie#17]
Hello,

I am trying to get the IMDB reviews for a given movie and I found your Python package which does that. Thanks for implementing it.

I was using the function get_title_reviews("tt2294629") to access the reviews. But it seems that it returns only the first 10 reviews. It was meant to be like that? Is it possible to get somehow all the reviews?

Kind regards,
Andrea

**Comment by richardasaurus** [comment]
The functionality to return more reviews is now in version 3.0.0

```python
get_title_reviews("tt0468569", max_results=15)
```

Version 3.0.0 also contains other changes so checkout the changelog before blindly installing it https://github.com/richardasaurus/imdb-pie/blob/master/HISTORY.rst#300-2015-06-12

**Comment by adalex2001** [comment]
Thank you!
Andrea
