### ISSUE TITLE
Retrieve IMDB recommendations

### ISSUE THREAD

**Issue by boompig** [richardasaurus/imdb-pie#19]
Add functionality to retrieve IMDB recommendations for an existing title

**Comment by richardasaurus** [comment]
Not sure if this is impossible with the api, will need some investigation. Also imdb recommendations are fairly poor

**Comment by VeNoMouS** [comment]
is that the same as similarities?  new api has call to `https://api.imdbws.com/template/imdb-ios-writable/title-similarities-v1.jstl/render?region=NZ&tconst=tt5519340&titleType=movie`

**Comment by richardasaurus** [comment]
added `get_title_similarities` method. please check if that fits what you want and reopen this if not 👍
