### ISSUE TITLE
Can't Retrieve an actor's credits

### ISSUE THREAD

**Issue by luzer** [richardasaurus/imdb-pie#26]
i want to get the actors/writers of a series (done)
but not able to get each of those actor's roles (all the values of P are empty)

thanks for the great library

```
  #get all credits/cast from each esisode
    for e in imdb.get_episodes('tt0098904'):
        ee = imdb.get_title_by_id(e.imdb_id)
        for c in ee.credits: #get credits from the episode, not the series                
            p = imdb.get_person_by_id(c.imdb_id)
            print p
            print p.roles
            print p.attr
            print p.job
            print p.token
            print p.label
```

**Comment by richardasaurus** [comment]
I think this will work

```python
  #get all credits/cast from each esisode
    for e in imdb.get_episodes('tt0098904'):
        ee = imdb.get_title_by_id(e.imdb_id)
        for c in ee.credits: #get credits from the episode, not the series                
            print c
            print c.roles
            print c.attr
            print c.job
            print c.token
            print c.label
```

The problem was that when you do `get_person_by_id`, that API response has no data on it about the episode for that person, so the data is not found on the `Person` object. While the API response which populated `ee.credits` does.

**Comment by luzer** [comment]
sorry, i dont think i was clear:
for each actor/writer in a series, i am trying to find out what **else** that actor has been in.
ie... also know for:

![screen shot 2016-08-29 at 7 55 19 pm](https://cloud.githubusercontent.com/assets/3173585/18071276/8c435396-6e22-11e6-9c77-ed96045dd15b.png)

**Comment by richardasaurus** [comment]
@luzer I see now. That data is available, just not added to the `Person` object. I can probably get that done in the next day or two

**Comment by luzer** [comment]
thanks @richardasaurus i wasnt aware of that. 
no rush- i have workarounds for now (using  imdbpy etc)

**Comment by luzer** [comment]
but GOIM doesnt support writers or directors

so i am trying to find the overlap between shows- people that acted in, wrote for SHOW A and also showed up in others..

**Comment by free-puppies** [comment]
Did you have any success with this? Interested in doing something similar. Thank you!

**Comment by richardasaurus** [comment]
please try again with the new version (5.0.0) and reopen if there is still an issue
