### ISSUE TITLE
Watchlist management

### ISSUE THREAD

**Issue by silverWeaver** [richardasaurus/imdb-pie#28]
Hello,

Is there any way to add a title to a watchlist? Or generally management of a watchlist..

**Comment by SIGINT** [comment]
That'd be a great feature, but wouldn't it require the API authenticate on behalf of an IMDb user to modify a watchlist?

@richardasaurus: Really great module - thanks!

**Comment by richardasaurus** [comment]
I'm sure there's a way, but I don't know. You could find out by watching traffic while using the iphone application

**Comment by richardasaurus** [comment]
Closing for now, if someone finds the api endpoints for this let me know and we can add it
