### ISSUE TITLE
Singular Credit

### ISSUE THREAD

**Issue by free-puppies** [richardasaurus/imdb-pie#32]
Trying to pull all the writing credits for a series, apparently the token "writers" applies only to those with multiple credits, thus skipping the writers who are a "writer" and only have one credit. There is no token in the singular. Any idea how to get the names of anyone credited as a writer and not just the writers of multiple episodes?  

Thank you!

**Comment by richardasaurus** [comment]
this lib has just recieved a big update, so please try again and reopen if still relevant
