### ISSUE TITLE
Remove your API TOKEN

### ISSUE THREAD

**Issue by tommagic** [richardasaurus/imdb-pie#33]
I would remove your API token from the constants file and add it to the instantiation of the  `Imdb` object

**Comment by MoHD20** [comment]
Could anyone obtains an API token for himself? or It's just this API? and how did he obtained it?
if it's just this, my thought is that he sniffed it from the iOS app, right? but How?

**Comment by richardasaurus** [comment]
@tommagic PR's very welcome
