### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by nichcuta** [richardasaurus/imdb-pie#35]
Hi,

Today, i keep getting "('Connection aborted.', error(104, 'Connection reset by peer'))" Error.

Perhaps the service is temporary down or?

**Comment by heyoni** [comment]
I just did a quick `search_for_title()' and it worked for me.

**Comment by nichcuta** [comment]
It works again, perhaps it had some issues from IMDB side. Thanks for the confirmation :)
