### ISSUE TITLE
Shouldn't be results in 'search_for_title' customisable?

### ISSUE THREAD

**Issue by fernand0** [richardasaurus/imdb-pie#40]
Hello,

in  def search_for_title(self, title): the results are of four types:  'title_popular', 'title_exact', 'title_approx', 'title_substring'. 
Maybe this should customisable and I'm thinking about two solutions but, maybe, there are better ones:
- An aditional parameter in the function with a list of the 'acceptable' results (for example: [ 'title_exact', 'title_substring']
- Returning the result with one more value in  result_item, which can indicate the type of result in such a way that we could filter it in a program calling the function.
Something like:

```
    result_item = {
                        'title': html_unescaped(result['title']),
                        'year': year,
                        'imdb_id': result['id'],
                        'target_result': 'key'
    }
```
or something similar.

**Comment by richardasaurus** [comment]
imdb recently totally removed the xml search api, so this wouldn't be possible anymore. 

i've managed to fix search by making it use the search suggestions api (called when you type in the search box on the website and the results come up as you type). 

this is fixed in imdbpie `4.4.0`.
