### ISSUE TITLE
find creator of series

### ISSUE THREAD

**Issue by allefeld** [richardasaurus/imdb-pie#42]
How can I determine the "creator" of a TV series?

For example the "full cast & crew" page for  "Alias (2001)" <http://www.imdb.com/title/tt0285333/fullcredits?ref_=tt_ov_st_sm> lists J.J. Abrams twice, 5th under "Series Directed by" and 1st under "Series Writing Credits". His writing credit has the additional remark "(created by)".

When I access the data via imdb-pie

    title = imdb.get_title_by_id('tt0285333')

the full cast & crew is available as `title.credits`, and Abrams appears as `title.credits[4]` and `title.credits[15]`, with the `token = 'directors'` and `'writers'`, respectively. So far so good. However, I can't find the "(created by)" label in any field.

The information should also appear in `title.creators`, which is however empty.

The best thing I could find is `title.writers_summary` – is that the correct way?

**Comment by richardasaurus** [comment]
Imdb api data isn't 100% perfect, so some titles will not have data to populate `imdb_title.creators`. 

you can sometimes find the creator from the "attr" attribute on the writers_summary results. e.g:

```python
>> title=self.imdb.get_title_by_id('tt0285333')
>> title.writers_summary
[<Person: 'J.J. Abrams' ('nm0009190')>]
>> title.writers_summary[0].attr
'(created by)'
```
