### ISSUE TITLE
Export info as json

### ISSUE THREAD

**Issue by pgjensen** [richardasaurus/imdb-pie#46]
Is there a way to dump your object created by get_title_by_id(imdbid) into a JSON string?  json.dumps doesn't work since you have custom objects for Title, Person, etc.

**Comment by richardasaurus** [comment]
Not at the moment. A flag could be added to the client init method to return raw responses instead of objects. I don't have time at the moment but PRs are very welcome.

**Comment by richardasaurus** [comment]
version 5.0.0 is now raw responses for each method
