### ISSUE TITLE
Add support for writers, directors, characters and actors

### ISSUE THREAD

**Issue by binhex** [richardasaurus/imdb-pie#58]
Hi, any chance you could include support to grab writers, directors, characters and actor information, you can get all of this from the api via 'fullcredits', you can then grab all of the info from the following keys (pseudo code):-

```
writers = full_credits['credits']['writer']
for i in writers:

    print(i['name'])

directors = full_credits['credits']['director']
for i in directors:

    print(i['name'])

cast = full_credits['credits']['cast']
for i in cast:

    print(i['characters'])
    print(i['name'])
```

**Comment by richardasaurus** [comment]
`get_title_credits` method should return this, its missing from the README file. will add it

**Comment by binhex** [comment]
Thanks @richardasaurus and i really appreciate the speed at which you have fixed up your code, awesome work!.
