### ISSUE TITLE
get_episodes function depreciated?

### ISSUE THREAD

**Issue by nichcuta** [richardasaurus/imdb-pie#59]
Hi,

i noticed that the get_episodes function is no longer available. I use to use this to retrieve release date information per episode, hence how can i reproduce such results with current functions?

Thanks!

**Comment by richardasaurus** [comment]
This is all documented here: https://github.com/richardasaurus/imdb-pie#available-methods

**Comment by duramato** [comment]
Just FYI, I'm probably going to implement this endpoint back.

**Comment by richardasaurus** [comment]
@duramato No need, it already exists: https://github.com/richardasaurus/imdb-pie#get_title_episodes

**Comment by duramato** [comment]
@richardasaurus That doesn't have specific air dates, only the year. There's an endpoint that has the full info.
