### ISSUE TITLE
Use attrdict for returned entities

### ISSUE THREAD

**Issue by mueslo** [richardasaurus/imdb-pie#61]
[attrdict](https://github.com/bcj/AttrDict) allows much more comfortable addressing of values, e.g.

`movie.base.title` instead of `movie['base']['title']`

**Comment by duramato** [comment]
imdb-pie returns the "raw" json response IMDb returns. I can't speak for @richardasaurus , but while I would also find that useful, I think that's something more suitable for the script integrating imdb-pie to do.

**Comment by richardasaurus** [comment]
As above, you can do this yourself with something like this:

```python
from imdbpie import Imdb
from attrdict import AttrDict

class MyImdb(Imdb):

    def _get(self, *args, **kwargs):
        return AttrDict(super()._get(*args, **kwargs))
```

`_get` is called to make all the api calls, so you can just override this. although be careful when upgrading to new lib versions as that is a private method so may be renamed in the future
