### ISSUE TITLE
Do we really need to check the imdb for each request?

### ISSUE THREAD

**Issue by p0psicles** [richardasaurus/imdb-pie#62]
https://github.com/richardasaurus/imdb-pie/blob/028d139ceaa6aeeff9734fc3b3ac0f006caf7b03/src/imdbpie/imdbpie.py#L111

For now we do not have any other means to get the episode release date, then using this route for every episode.
But because we verify the imdb id in each call, it will do twice the amount of requests.

**Comment by richardasaurus** [comment]
`validate_imdb_id` doesn't make a http request

**Comment by p0psicles** [comment]
I'm sorry, your absolutely right. Must have made a mistake on my end.
