### ISSUE TITLE
SSLError: certificate verify failed (youtubeproxy.org)

### ISSUE THREAD

**Issue by blueyed** [richardasaurus/imdb-pie#8]
I have seen the following error, which can be worked around using `verify=False` with `requests.get`.

The reason is that the certificate of youtubeproxy.org expired:

> The certificate expired on 01.06.2013 21:33. The current time is 07.04.2014 14:44.

Maybe another proxy could be used by default?

Also the proxy should be made configurable probably.

    /usr/local/lib/python2.7/dist-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
        329         except (_SSLError, _HTTPError) as e:
        330             if isinstance(e, _SSLError):
    --> 331                 raise SSLError(e)
        332             elif isinstance(e, TimeoutError):
        333                 raise Timeout(e)

    SSLError: [Errno 1] _ssl.c:509: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by richardasaurus** [comment]
now complete in 2.0.0
